export type Recipe = {
  id: string
  name: string
  imageUrl: string | null
  tags: string[]
  isFavorite: boolean
  duration?: string
  category?: string
}

export type RecipeDetail = {
  servings: string
  ingredients: string[]
  steps: string[]
}

// Tags (English): Quick · Vegan · Gluten-free · Seasonal
// Categories (English): Breakfast · Main · Snack & side
// Recipe names, ingredients and steps stay in German (authentic Swiss content).

export const neueRezepte: Recipe[] = [
  { id: '1', name: 'Omeletten mit Hackfleisch', imageUrl: 'https://images.unsplash.com/photo-1525184782196-8e2ded604bf7?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free', 'Seasonal'], isFavorite: false, duration: '25 min' },
  { id: '2', name: 'Süsskartoffel-Gemüse-Gratin', imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan', 'Seasonal'], isFavorite: false, duration: '45 min' },
  { id: '5', name: 'Lachs mit Zitronenbutter', imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: false, duration: '20 min' },
  { id: '6', name: 'Thai-Curry mit Kokosmilch', imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop', tags: ['Vegan', 'Seasonal'], isFavorite: false, duration: '35 min' },
]

export const favoritenRezepte: Recipe[] = [
  { id: '3', name: 'Pasta Carbonara', imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop', tags: ['Quick', 'Seasonal'], isFavorite: true, duration: '25 min' },
  { id: '4', name: 'Buddha Bowl mit Quinoa', imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free'], isFavorite: true, duration: '30 min' },
  { id: '7', name: 'Poulet-Wrap mit Avocado', imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop', tags: ['Quick'], isFavorite: true, duration: '15 min' },
  { id: '8', name: 'Risotto mit Pilzen', imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop', tags: ['Seasonal', 'Gluten-free'], isFavorite: true, duration: '40 min' },
]

export const allFavoritenRezepte: Recipe[] = [
  { id: 'f1', name: 'Avocado-Toast mit pochiertem Ei', imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop', tags: ['Quick'], isFavorite: true, duration: '15 min', category: 'Breakfast' },
  { id: 'f2', name: 'Bircher Müsli', imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free'], isFavorite: true, duration: '10 min', category: 'Breakfast' },
  { id: 'f3', name: 'Shakshuka', imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=400&h=300&fit=crop', tags: ['Gluten-free', 'Seasonal'], isFavorite: true, duration: '25 min', category: 'Breakfast' },
  { id: 'f4', name: 'Banana-Pancakes', imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop', tags: ['Quick'], isFavorite: true, duration: '15 min', category: 'Breakfast' },
  { id: 'f5', name: 'Thai Glasnudelsuppe', imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: true, duration: '20 min', category: 'Main' },
  { id: 'f6', name: 'Lachs-Teriyaki mit Reis', imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop', tags: ['Gluten-free'], isFavorite: true, duration: '30 min', category: 'Main' },
  { id: 'f7', name: 'One-Pot Pasta Arrabiata', imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan'], isFavorite: true, duration: '25 min', category: 'Main' },
  { id: 'f8', name: 'Kürbis-Risotto', imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop', tags: ['Seasonal', 'Gluten-free'], isFavorite: true, duration: '40 min', category: 'Main' },
  { id: 'f9', name: 'Gebackener Feta mit Gemüse', imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free', 'Seasonal'], isFavorite: true, duration: '30 min', category: 'Main' },
  { id: 'f10', name: 'Poulet-Satay mit Erdnusssauce', imageUrl: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=400&h=300&fit=crop', tags: ['Gluten-free'], isFavorite: true, duration: '35 min', category: 'Main' },
  { id: 'f11', name: 'Gemüse-Curry mit Kichererbsen', imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop', tags: ['Vegan', 'Seasonal'], isFavorite: true, duration: '35 min', category: 'Main' },
  { id: 'f12', name: 'Zucchini-Puffer mit Dip', imageUrl: 'https://images.unsplash.com/photo-1606756790138-261d2b21cd75?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: true, duration: '20 min', category: 'Snack & side' },
  { id: 'f13', name: 'Hummus mit Ofengemüse', imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free'], isFavorite: true, duration: '30 min', category: 'Snack & side' },
  { id: 'f14', name: 'Caprese-Salat', imageUrl: 'https://images.unsplash.com/photo-1608032077018-c9aad9565d29?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free', 'Seasonal'], isFavorite: true, duration: '10 min', category: 'Snack & side' },
  { id: 'f15', name: 'Süsskartoffel-Pommes', imageUrl: 'https://images.unsplash.com/photo-1623238912680-26fc5ffb57e4?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free'], isFavorite: true, duration: '35 min', category: 'Snack & side' },
]

export const eigeneRezepte: Recipe[] = [
  { id: 'e1', name: 'Omas Kartoffelsalat', imageUrl: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=400&h=300&fit=crop', tags: ['Gluten-free', 'Seasonal'], isFavorite: true, duration: '40 min', category: 'Main' },
  { id: 'e2', name: 'Mamas Lasagne', imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&h=300&fit=crop', tags: ['Seasonal'], isFavorite: false, duration: '90 min', category: 'Main' },
  { id: 'e3', name: 'Zürcher Geschnetzeltes', imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', tags: ['Gluten-free'], isFavorite: true, duration: '35 min', category: 'Main' },
  { id: 'e4', name: 'Overnight Oats mit Beeren', imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&h=300&fit=crop', tags: ['Vegan', 'Quick'], isFavorite: false, duration: '5 min', category: 'Breakfast' },
  { id: 'e5', name: 'Selbstgemachte Pizza', imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop', tags: ['Vegan'], isFavorite: true, duration: '60 min', category: 'Main' },
  { id: 'e6', name: 'Guetzli (Weihnachtskekse)', imageUrl: 'https://images.unsplash.com/photo-1481391032119-d89fee407e44?w=400&h=300&fit=crop', tags: ['Seasonal'], isFavorite: false, duration: '120 min', category: 'Snack & side' },
]

export const saisonaleRezepte: Recipe[] = [
  { id: 's1', name: 'Kürbissuppe mit Ingwer', imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free', 'Seasonal'], isFavorite: false, duration: '30 min', category: 'Main' },
  { id: 's2', name: 'Spargel mit Hollandaise', imageUrl: 'https://images.unsplash.com/photo-1515516969-d4008cc6241a?w=400&h=300&fit=crop', tags: ['Gluten-free', 'Seasonal'], isFavorite: true, duration: '25 min', category: 'Main' },
  { id: 's3', name: 'Randen-Risotto', imageUrl: 'https://images.unsplash.com/photo-1633436375153-d7045cb93e38?w=400&h=300&fit=crop', tags: ['Gluten-free', 'Seasonal'], isFavorite: false, duration: '45 min', category: 'Main' },
  { id: 's4', name: 'Erdbeerkuchen', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop', tags: ['Seasonal'], isFavorite: true, duration: '50 min', category: 'Snack & side' },
  { id: 's5', name: 'Ratatouille', imageUrl: 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free', 'Seasonal'], isFavorite: false, duration: '55 min', category: 'Main' },
  { id: 's6', name: 'Federkohl-Salat mit Granatapfel', imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop', tags: ['Vegan', 'Gluten-free', 'Seasonal'], isFavorite: true, duration: '15 min', category: 'Snack & side' },
  { id: 's7', name: 'Pilz-Ragout mit Polenta', imageUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&h=300&fit=crop', tags: ['Gluten-free', 'Seasonal'], isFavorite: false, duration: '40 min', category: 'Main' },
  { id: 's8', name: 'Zwetschgenwähe', imageUrl: 'https://images.unsplash.com/photo-1509461399763-ae67a981b254?w=400&h=300&fit=crop', tags: ['Seasonal'], isFavorite: false, duration: '60 min', category: 'Snack & side' },
  { id: 's9', name: 'Lauch-Quiche', imageUrl: 'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=400&h=300&fit=crop', tags: ['Seasonal'], isFavorite: true, duration: '50 min', category: 'Main' },
  { id: 's10', name: 'Minestrone', imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop', tags: ['Vegan', 'Seasonal'], isFavorite: false, duration: '35 min', category: 'Main' },
]

export const schnelleRezepte: Recipe[] = [
  { id: 'q1', name: 'Rührei mit Schnittlauch', imageUrl: 'https://images.unsplash.com/photo-1525184782196-8e2ded604bf7?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: false, duration: '10 min', category: 'Breakfast' },
  { id: 'q2', name: 'Tomaten-Mozzarella-Sandwich', imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop', tags: ['Quick'], isFavorite: true, duration: '10 min', category: 'Snack & side' },
  { id: 'q3', name: 'Aglio e Olio', imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan'], isFavorite: false, duration: '15 min', category: 'Main' },
  { id: 'q4', name: 'Griechischer Salat', imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: true, duration: '10 min', category: 'Snack & side' },
  { id: 'q5', name: 'Wrap mit Poulet & Hummus', imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop', tags: ['Quick'], isFavorite: false, duration: '15 min', category: 'Main' },
  { id: 'q6', name: 'Smoothie Bowl', imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan', 'Gluten-free'], isFavorite: true, duration: '10 min', category: 'Breakfast' },
  { id: 'q7', name: 'Bruschetta mit Tomaten', imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan'], isFavorite: false, duration: '15 min', category: 'Snack & side' },
  { id: 'q8', name: 'Gebratene Udon-Nudeln', imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan'], isFavorite: false, duration: '20 min', category: 'Main' },
  { id: 'q9', name: 'Omelett mit Kräutern', imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400&h=300&fit=crop', tags: ['Quick', 'Gluten-free'], isFavorite: true, duration: '10 min', category: 'Breakfast' },
  { id: 'q10', name: 'Couscous-Salat', imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&h=300&fit=crop', tags: ['Quick', 'Vegan'], isFavorite: false, duration: '15 min', category: 'Snack & side' },
]

const allRecipesMap = new Map<string, Recipe>()
for (const r of [...neueRezepte, ...favoritenRezepte, ...allFavoritenRezepte, ...eigeneRezepte, ...saisonaleRezepte, ...schnelleRezepte]) {
  allRecipesMap.set(r.id, r)
}
export const allRecipes: Recipe[] = Array.from(allRecipesMap.values())

const recipeDetails: Record<string, RecipeDetail> = {
  '1': { servings: '2 Portionen', ingredients: ['4 Eier', '200 g Hackfleisch', '1 Zwiebel, gewürfelt', '1 EL Olivenöl', 'Salz, Pfeffer', 'Frische Petersilie'], steps: ['Hackfleisch mit Zwiebeln in Olivenöl anbraten, würzen.', 'Eier verquirlen, salzen und pfeffern.', 'Eier über das Hackfleisch giessen und bei mittlerer Hitze stocken lassen.', 'Omelette falten, mit Petersilie garnieren und servieren.'] },
  '2': { servings: '4 Portionen', ingredients: ['2 Süsskartoffeln, geschält und gewürfelt', '1 Zucchini, in Scheiben', '1 Peperoni, gewürfelt', '200 ml Rahm', '100 g geriebener Käse', '1 EL Olivenöl', 'Salz, Pfeffer, Muskatnuss'], steps: ['Ofen auf 200°C vorheizen.', 'Süsskartoffeln 10 Min. vorkochen, abtropfen lassen.', 'Gemüse in eine Gratinform schichten.', 'Rahm mit Gewürzen mischen, darüber giessen.', 'Käse darüber streuen und 25 Min. überbacken.'] },
  '5': { servings: '2 Portionen', ingredients: ['2 Lachsfilets', '50 g Butter', '1 Zitrone', '2 Knoblauchzehen', 'Salz, Pfeffer', 'Frischer Dill'], steps: ['Lachs salzen und pfeffern.', 'In einer Pfanne mit etwas Öl von beiden Seiten je 4 Min. braten.', 'Butter, Knoblauch und Zitronensaft in einer kleinen Pfanne aufschäumen.', 'Zitronenbutter über den Lachs giessen, mit Dill garnieren.'] },
  '6': { servings: '4 Portionen', ingredients: ['400 ml Kokosmilch', '2 EL rote Currypaste', '300 g Tofu, gewürfelt', '1 Peperoni, in Streifen', '200 g Brokkoli', '2 EL Sojasauce', 'Jasminreis als Beilage'], steps: ['Currypaste in etwas Öl anrösten.', 'Kokosmilch einrühren und aufkochen.', 'Gemüse und Tofu dazugeben, 15 Min. köcheln lassen.', 'Mit Sojasauce abschmecken.', 'Mit Jasminreis servieren.'] },
  '3': { servings: '2 Portionen', ingredients: ['200 g Spaghetti', '100 g Guanciale oder Speck', '2 Eigelb', '50 g Pecorino, gerieben', '1 Knoblauchzehe', 'Schwarzer Pfeffer'], steps: ['Pasta in Salzwasser al dente kochen.', 'Guanciale knusprig braten, Knoblauch mitbraten und entfernen.', 'Eigelb mit Pecorino und Pfeffer verrühren.', 'Pasta zum Guanciale geben, vom Herd nehmen.', 'Ei-Käse-Mischung unterrühren, sofort servieren.'] },
  '4': { servings: '2 Portionen', ingredients: ['150 g Quinoa', '1 Avocado', '100 g Kichererbsen (Dose)', '1 Rüebli, geraspelt', '50 g Rotkabis, fein geschnitten', 'Tahini-Dressing', 'Sesam'], steps: ['Quinoa nach Packungsanleitung kochen und abkühlen lassen.', 'Avocado halbieren und in Scheiben schneiden.', 'Alle Zutaten in einer Bowl anrichten.', 'Mit Tahini-Dressing beträufeln und Sesam bestreuen.'] },
  '7': { servings: '2 Portionen', ingredients: ['2 grosse Tortillas', '200 g Pouletbrust, gegrillt und geschnitten', '1 Avocado, in Scheiben', 'Eisbergsalat', '2 EL Joghurt-Sauce', 'Limettensaft'], steps: ['Tortillas kurz in einer Pfanne erwärmen.', 'Joghurt-Sauce auf den Tortillas verteilen.', 'Poulet, Avocado und Salat darauf verteilen.', 'Mit Limettensaft beträufeln, einrollen und servieren.'] },
  '8': { servings: '4 Portionen', ingredients: ['300 g Risotto-Reis', '300 g gemischte Pilze', '1 Zwiebel, fein gewürfelt', '150 ml Weisswein', '800 ml Bouillon', '50 g Parmesan', '2 EL Butter'], steps: ['Zwiebel in Butter andünsten, Pilze dazu und kurz mitbraten.', 'Reis dazugeben und glasig rühren.', 'Mit Weisswein ablöschen.', 'Bouillon schrittweise einrühren, ca. 18 Min.', 'Parmesan unterrühren, mit Pfeffer abschmecken.'] },
  'f1': { servings: '1 Portion', ingredients: ['2 Scheiben Sauerteigbrot', '1 Avocado', '2 Eier', 'Chiliflocken', 'Salz, Pfeffer', 'Sprossen'], steps: ['Wasser mit einem Schuss Essig zum Sieden bringen.', 'Eier einzeln ins Wasser gleiten lassen, 3 Min. pochieren.', 'Brot toasten, Avocado darauf verteilen und zerdrücken.', 'Pochierte Eier darauflegen, mit Chili und Sprossen garnieren.'] },
  'f2': { servings: '2 Portionen', ingredients: ['200 g Haferflocken', '400 ml Hafermilch', '2 Äpfel, geraspelt', '2 EL Zitronensaft', '2 EL Agavendicksaft', 'Beeren und Nüsse zum Garnieren'], steps: ['Haferflocken mit Hafermilch mischen.', 'Über Nacht im Kühlschrank ziehen lassen.', 'Morgens Äpfel, Zitronensaft und Agavendicksaft unterrühren.', 'Mit frischen Beeren und Nüssen garnieren.'] },
  'f3': { servings: '2 Portionen', ingredients: ['1 Dose gehackte Tomaten', '1 Peperoni, gewürfelt', '1 Zwiebel, gewürfelt', '4 Eier', '1 TL Kreuzkümmel', '1 TL Paprikapulver', 'Frische Koriander'], steps: ['Zwiebel und Peperoni in Olivenöl andünsten.', 'Gewürze kurz mitrösten, Tomaten dazugeben.', '10 Min. einkochen lassen.', 'Mulden formen, Eier hineinschlagen.', 'Zugedeckt 5–8 Min. stocken lassen. Mit Koriander servieren.'] },
  'f4': { servings: '2 Portionen', ingredients: ['2 reife Bananen', '3 Eier', '1 EL Mehl (optional)', 'Butter zum Braten', 'Ahornsirup', 'Frische Beeren'], steps: ['Bananen mit einer Gabel zerdrücken.', 'Eier unterrühren, optional Mehl dazugeben.', 'Kleine Portionen in Butter goldbraun braten.', 'Mit Ahornsirup und Beeren servieren.'] },
  'f5': { servings: '2 Portionen', ingredients: ['100 g Glasnudeln', '500 ml Pouletbouillon', '200 g Pouletbrust, in Streifen', '1 Rüebli, in feinen Streifen', '2 Frühlingszwiebeln', '2 EL Fischsauce', 'Limette, Koriander'], steps: ['Bouillon aufkochen, Poulet darin garen.', 'Glasnudeln und Rüebli dazugeben, 5 Min. kochen.', 'Mit Fischsauce und Limettensaft abschmecken.', 'Mit Frühlingszwiebeln und Koriander servieren.'] },
  'f6': { servings: '2 Portionen', ingredients: ['2 Lachsfilets', '3 EL Sojasauce', '2 EL Mirin', '1 EL Honig', '1 TL Ingwer, gerieben', 'Jasminreis', 'Sesam'], steps: ['Sojasauce, Mirin, Honig und Ingwer verrühren.', 'Lachs darin 15 Min. marinieren.', 'In einer Pfanne von beiden Seiten je 4 Min. braten.', 'Restliche Marinade einkochen und darüber giessen.', 'Mit Reis und Sesam servieren.'] },
  'f7': { servings: '4 Portionen', ingredients: ['400 g Penne', '1 Dose gehackte Tomaten', '2 Knoblauchzehen', '1 TL Chiliflocken', '2 EL Olivenöl', 'Frisches Basilikum', 'Salz'], steps: ['Knoblauch und Chili in Olivenöl andünsten.', 'Tomaten und ungekochte Pasta dazugeben.', 'Mit 400 ml Wasser aufgiessen.', 'Zugedeckt 12–15 Min. kochen, zwischendurch rühren.', 'Mit Basilikum servieren.'] },
  'f8': { servings: '4 Portionen', ingredients: ['300 g Risotto-Reis', '400 g Kürbis, gewürfelt', '1 Zwiebel', '150 ml Weisswein', '800 ml Bouillon', '50 g Parmesan', 'Salbeiblätter'], steps: ['Kürbis im Ofen bei 200°C 20 Min. rösten.', 'Zwiebel in Butter andünsten, Reis dazugeben.', 'Mit Weisswein ablöschen, Bouillon schrittweise einrühren.', 'Kürbis und Parmesan unterrühren.', 'Mit gebratenen Salbeiblättern servieren.'] },
  'f9': { servings: '4 Portionen', ingredients: ['200 g Feta', '2 Peperoni', '1 Zucchini', '250 g Cherrytomaten', '2 EL Olivenöl', '1 TL Oregano', 'Frisches Brot'], steps: ['Ofen auf 200°C vorheizen.', 'Gemüse grob würfeln, in eine Ofenform geben.', 'Feta in die Mitte legen, alles mit Öl beträufeln.', 'Oregano darüber streuen, 25 Min. backen.', 'Feta zerdrücken, mit Brot servieren.'] },
  'f10': { servings: '4 Portionen', ingredients: ['500 g Pouletbrust, in Streifen', '3 EL Erdnussbutter', '2 EL Sojasauce', '1 EL Limettensaft', '1 TL Sambal Oelek', '2 EL Kokosmilch', 'Holzspiesse'], steps: ['Poulet auf Spiesse stecken.', 'Erdnussbutter, Sojasauce, Limettensaft, Sambal und Kokosmilch verrühren.', 'Spiesse mit der Hälfte der Sauce marinieren, 30 Min. ziehen lassen.', 'Auf dem Grill oder in der Pfanne je Seite 4 Min. braten.', 'Mit restlicher Erdnusssauce servieren.'] },
  'f11': { servings: '4 Portionen', ingredients: ['1 Dose Kichererbsen', '400 ml Kokosmilch', '2 EL Currypaste', '300 g Spinat', '1 Zwiebel', '2 Knoblauchzehen', 'Reis als Beilage'], steps: ['Zwiebel und Knoblauch in Öl andünsten.', 'Currypaste mitrösten, Kokosmilch einrühren.', 'Kichererbsen dazugeben, 15 Min. köcheln.', 'Spinat unterheben, zusammenfallen lassen.', 'Mit Reis servieren.'] },
  'f12': { servings: '2 Portionen', ingredients: ['2 Zucchini, geraspelt', '2 Eier', '3 EL Mehl', '50 g Feta, zerbröselt', 'Salz, Pfeffer', '150 g Joghurt', '1 Knoblauchzehe'], steps: ['Zucchini ausdrücken, mit Eiern, Mehl und Feta mischen.', 'Kleine Puffer formen.', 'In Öl von beiden Seiten goldbraun braten.', 'Joghurt mit Knoblauch und Salz verrühren.', 'Puffer mit Dip servieren.'] },
  'f13': { servings: '4 Portionen', ingredients: ['400 g Kichererbsen (Dose)', '3 EL Tahini', '2 Knoblauchzehen', 'Saft von 1 Zitrone', '2 Peperoni', '1 Aubergine', '2 EL Olivenöl'], steps: ['Kichererbsen, Tahini, Knoblauch und Zitronensaft pürieren.', 'Gemüse in Stücke schneiden, mit Öl beträufeln.', 'Im Ofen bei 200°C 25 Min. rösten.', 'Hummus auf einem Teller verteilen.', 'Ofengemüse darauf anrichten.'] },
  'f14': { servings: '2 Portionen', ingredients: ['3 Tomaten, in Scheiben', '200 g Mozzarella', 'Frisches Basilikum', '2 EL Olivenöl', 'Balsamico-Reduktion', 'Salz, Pfeffer'], steps: ['Tomaten und Mozzarella abwechselnd auf einem Teller anrichten.', 'Mit Basilikumblättern garnieren.', 'Olivenöl und Balsamico darüber träufeln.', 'Mit Salz und Pfeffer würzen.'] },
  'f15': { servings: '2 Portionen', ingredients: ['2 grosse Süsskartoffeln', '2 EL Olivenöl', '1 TL Paprikapulver', '1 TL Knoblauchpulver', 'Salz', 'Ketchup oder Aioli'], steps: ['Ofen auf 220°C vorheizen.', 'Süsskartoffeln in Stifte schneiden.', 'Mit Öl und Gewürzen mischen.', 'Auf einem Blech verteilen, 25–30 Min. backen.', 'Zwischendurch wenden. Mit Dip servieren.'] },
  'e1': { servings: '4 Portionen', ingredients: ['1 kg festkochende Kartoffeln', '1 Zwiebel, fein gewürfelt', '200 ml Bouillon', '3 EL Essig', '4 EL Sonnenblumenöl', 'Schnittlauch', 'Salz, Pfeffer'], steps: ['Kartoffeln kochen, noch warm pellen und in Scheiben schneiden.', 'Bouillon mit Essig und Öl verrühren.', 'Über die Kartoffeln giessen, Zwiebeln unterheben.', '30 Min. durchziehen lassen.', 'Mit Schnittlauch garnieren.'] },
  'e2': { servings: '6 Portionen', ingredients: ['500 g Hackfleisch', '12 Lasagneblätter', '2 Dosen gehackte Tomaten', '500 ml Béchamelsauce', '200 g geriebener Käse', '1 Zwiebel', '2 Knoblauchzehen'], steps: ['Hackfleisch mit Zwiebel und Knoblauch anbraten.', 'Tomaten dazugeben, 20 Min. einkochen lassen.', 'In einer Form abwechselnd Sauce, Nudeln und Béchamel schichten.', 'Mit Käse bestreuen.', 'Bei 180°C 45 Min. backen.'] },
  'e3': { servings: '4 Portionen', ingredients: ['600 g Kalbsgeschnetzeltes', '200 g Champignons', '1 Zwiebel', '200 ml Rahm', '100 ml Weisswein', '1 EL Butter', 'Rösti als Beilage'], steps: ['Fleisch portionsweise in Butter scharf anbraten.', 'Zwiebel und Pilze andünsten.', 'Mit Weisswein ablöschen.', 'Rahm dazugeben, 5 Min. köcheln.', 'Fleisch zurückgeben, abschmecken. Mit Rösti servieren.'] },
  'e4': { servings: '1 Portion', ingredients: ['50 g Haferflocken', '150 ml Hafermilch', '1 EL Chiasamen', '1 EL Ahornsirup', 'Frische Beeren', 'Nüsse'], steps: ['Haferflocken, Milch, Chiasamen und Ahornsirup mischen.', 'Im Glas über Nacht in den Kühlschrank stellen.', 'Morgens mit Beeren und Nüssen toppen.'] },
  'e5': { servings: '4 Portionen', ingredients: ['500 g Pizzateig', '200 g Tomatensauce', '250 g Mozzarella', 'Belag nach Wahl', '1 EL Olivenöl', 'Frisches Basilikum'], steps: ['Ofen auf 250°C vorheizen (Ober-/Unterhitze).', 'Teig dünn ausrollen.', 'Tomatensauce verteilen, Mozzarella darüber verteilen.', 'Gewünschten Belag hinzufügen.', '10–12 Min. backen bis der Rand goldbraun ist.', 'Mit frischem Basilikum servieren.'] },
  'e6': { servings: 'Ca. 60 Stück', ingredients: ['250 g Butter', '200 g Zucker', '1 Ei', '500 g Mehl', '1 Prise Salz', '1 TL Vanilleextrakt', 'Puderzucker zum Bestäuben'], steps: ['Butter und Zucker schaumig rühren.', 'Ei und Vanille unterrühren.', 'Mehl und Salz dazugeben, zu einem glatten Teig verarbeiten.', '1 Std. im Kühlschrank ruhen lassen.', 'Ausrollen, Formen ausstechen.', 'Bei 180°C 10–12 Min. backen.'] },
  's1': { servings: '4 Portionen', ingredients: ['800 g Kürbis, gewürfelt', '1 Zwiebel', '1 Stück Ingwer (3 cm)', '400 ml Kokosmilch', '500 ml Bouillon', 'Kürbiskerne', 'Olivenöl'], steps: ['Zwiebel und Ingwer in Öl andünsten.', 'Kürbis dazugeben, mit Bouillon aufgiessen.', '20 Min. weich kochen.', 'Pürieren, Kokosmilch einrühren.', 'Mit Kürbiskernen garnieren.'] },
  's2': { servings: '2 Portionen', ingredients: ['500 g weisser Spargel', '3 Eigelb', '200 g Butter', '1 EL Zitronensaft', 'Salz, Pfeffer', '1 Prise Zucker'], steps: ['Spargel schälen und in Salzwasser mit Zucker 12–15 Min. kochen.', 'Für die Hollandaise: Eigelb mit 2 EL Wasser über Wasserbad aufschlagen.', 'Flüssige Butter langsam einrühren.', 'Mit Zitronensaft, Salz und Pfeffer abschmecken.', 'Spargel mit Hollandaise servieren.'] },
  's3': { servings: '4 Portionen', ingredients: ['300 g Risotto-Reis', '2 gekochte Randen, püriert', '1 Zwiebel', '150 ml Weisswein', '800 ml Bouillon', '50 g Ziegenkäse', 'Butter'], steps: ['Zwiebel in Butter andünsten, Reis dazugeben.', 'Mit Weisswein ablöschen.', 'Bouillon schrittweise einrühren, ca. 18 Min.', 'Randenpüree unterrühren.', 'Mit Ziegenkäse garnieren.'] },
  's4': { servings: '8 Stücke', ingredients: ['250 g Mehl', '125 g Butter', '80 g Zucker', '1 Ei', '500 g Erdbeeren', '200 ml Rahm', '2 EL Puderzucker'], steps: ['Mürbeteig aus Mehl, Butter, Zucker und Ei kneten.', '30 Min. kühlen, dann in Kuchenform drücken.', 'Blind bei 180°C 15 Min. backen.', 'Abkühlen lassen, Erdbeeren darauf verteilen.', 'Rahm steif schlagen, über die Erdbeeren geben.'] },
  's5': { servings: '4 Portionen', ingredients: ['2 Zucchini', '1 Aubergine', '2 Peperoni', '4 Tomaten', '2 Knoblauchzehen', '3 EL Olivenöl', 'Frischer Thymian'], steps: ['Alles Gemüse in gleichmässige Scheiben schneiden.', 'In einer Ofenform fächerartig anordnen.', 'Mit Öl beträufeln, Knoblauch und Thymian darüber.', 'Bei 180°C 45 Min. backen.', 'Heiss oder lauwarm servieren.'] },
  's6': { servings: '2 Portionen', ingredients: ['200 g Federkohl, entstielt', '1 Granatapfel', '50 g Walnüsse', '2 EL Olivenöl', '1 EL Zitronensaft', '1 EL Ahornsirup', 'Salz'], steps: ['Federkohl waschen und in Streifen schneiden.', 'Mit Olivenöl, Zitronensaft und Salz massieren.', 'Granatapfelkerne und Walnüsse darüber verteilen.', 'Mit Ahornsirup beträufeln.'] },
  's7': { servings: '4 Portionen', ingredients: ['500 g gemischte Pilze', '200 g Polenta', '800 ml Wasser', '1 Zwiebel', '2 Knoblauchzehen', '100 ml Weisswein', '2 EL Butter', 'Thymian'], steps: ['Polenta nach Packungsanleitung in Salzwasser kochen.', 'Zwiebel und Knoblauch in Butter andünsten.', 'Pilze dazugeben, 5 Min. braten.', 'Mit Weisswein ablöschen, einkochen lassen.', 'Ragout auf Polenta anrichten, mit Thymian garnieren.'] },
  's8': { servings: '8 Stücke', ingredients: ['250 g Kuchenteig (ausgerollt)', '800 g Zwetschgen, halbiert', '3 Eier', '150 ml Rahm', '80 g Zucker', '1 TL Zimt'], steps: ['Teig in eine gefettete Wähenform legen.', 'Zwetschgen darauf verteilen.', 'Eier, Rahm, Zucker und Zimt verquirlen.', 'Guss über die Zwetschgen giessen.', 'Bei 180°C 35–40 Min. backen.'] },
  's9': { servings: '6 Stücke', ingredients: ['1 Blätterteig', '3 Stangen Lauch', '200 ml Rahm', '3 Eier', '100 g geriebener Gruyère', 'Salz, Pfeffer, Muskatnuss'], steps: ['Blätterteig in eine Quicheform legen.', 'Lauch in Ringe schneiden und in Butter andünsten.', 'Eier, Rahm und Käse verrühren, würzen.', 'Lauch auf dem Teig verteilen, Guss darüber giessen.', 'Bei 190°C 30–35 Min. backen.'] },
  's10': { servings: '4 Portionen', ingredients: ['2 Rüebli', '2 Kartoffeln', '1 Zucchini', '200 g Bohnen', '1 Dose weisse Bohnen', '1 Dose Tomaten', '1 l Bouillon', 'Basilikum-Pesto'], steps: ['Gemüse in kleine Würfel schneiden.', 'In Olivenöl kurz andünsten.', 'Bouillon und Tomaten dazugeben, 20 Min. kochen.', 'Bohnen (Dose) dazugeben, 5 Min. weiterkochen.', 'Mit einem Löffel Pesto servieren.'] },
  'q1': { servings: '1 Portion', ingredients: ['3 Eier', '1 EL Butter', 'Schnittlauch', 'Salz, Pfeffer'], steps: ['Eier verquirlen, salzen und pfeffern.', 'Butter in einer Pfanne schmelzen.', 'Eier hineingeben und bei niedriger Hitze langsam stocken lassen.', 'Mit Schnittlauch bestreuen.'] },
  'q2': { servings: '1 Portion', ingredients: ['2 Scheiben Brot', '1 Tomate, in Scheiben', '1 Kugel Mozzarella', 'Frisches Basilikum', 'Olivenöl', 'Balsamico'], steps: ['Brot toasten.', 'Mozzarella und Tomaten darauf schichten.', 'Mit Basilikum, Olivenöl und Balsamico verfeinern.'] },
  'q3': { servings: '2 Portionen', ingredients: ['200 g Spaghetti', '4 Knoblauchzehen', '1 TL Chiliflocken', '4 EL Olivenöl', 'Petersilie', 'Salz'], steps: ['Spaghetti al dente kochen.', 'Knoblauch in Scheiben in Olivenöl goldbraun braten.', 'Chiliflocken dazugeben.', 'Pasta unterheben, mit Petersilie servieren.'] },
  'q4': { servings: '2 Portionen', ingredients: ['2 Tomaten', '1 Gurke', '1 rote Zwiebel', '100 g Feta', 'Kalamata-Oliven', '3 EL Olivenöl', 'Oregano'], steps: ['Gemüse grob würfeln.', 'Mit Oliven in einer Schüssel mischen.', 'Feta darüber bröseln.', 'Mit Olivenöl und Oregano anmachen.'] },
  'q5': { servings: '2 Portionen', ingredients: ['2 Tortillas', '200 g Pouletbrust, gegrillt', '3 EL Hummus', 'Eisbergsalat', '1 Tomate', 'Salz, Pfeffer'], steps: ['Hummus auf Tortillas verteilen.', 'Poulet, Salat und Tomaten darauf verteilen.', 'Würzen, einrollen und diagonal halbieren.'] },
  'q6': { servings: '1 Portion', ingredients: ['1 Banane (gefroren)', '100 g gefrorene Beeren', '150 ml Hafermilch', 'Granola', 'Kokosraspeln', 'Chiasamen'], steps: ['Banane und Beeren mit Hafermilch pürieren.', 'In eine Schüssel giessen.', 'Mit Granola, Kokos und Chiasamen toppen.'] },
  'q7': { servings: '2 Portionen', ingredients: ['1 Baguette', '4 Tomaten, gewürfelt', '2 Knoblauchzehen', 'Frisches Basilikum', '2 EL Olivenöl', 'Salz, Pfeffer'], steps: ['Baguette in Scheiben schneiden und toasten.', 'Tomaten mit Knoblauch, Basilikum und Öl mischen.', 'Auf die Brotscheiben verteilen.'] },
  'q8': { servings: '2 Portionen', ingredients: ['200 g Udon-Nudeln', '2 EL Sojasauce', '1 EL Sesamöl', '1 Rüebli, in Streifen', '1 Peperoni', '2 Frühlingszwiebeln', 'Sesam'], steps: ['Udon-Nudeln nach Packung kochen, abgiessen.', 'Gemüse im Wok bei hoher Hitze 3 Min. braten.', 'Nudeln, Sojasauce und Sesamöl dazugeben.', 'Alles 2 Min. schwenken, mit Sesam bestreuen.'] },
  'q9': { servings: '1 Portion', ingredients: ['3 Eier', '1 EL Butter', 'Frische Kräuter (Schnittlauch, Petersilie, Dill)', 'Salz, Pfeffer'], steps: ['Eier verquirlen, Kräuter unterrühren.', 'In Butter bei mittlerer Hitze stocken lassen.', 'Omelett zusammenklappen und servieren.'] },
  'q10': { servings: '2 Portionen', ingredients: ['200 g Couscous', '200 ml heisses Wasser', '1 Gurke, gewürfelt', '200 g Cherrytomaten', 'Frische Minze', '3 EL Olivenöl', 'Saft von 1 Zitrone'], steps: ['Couscous mit heissem Wasser übergiessen, 5 Min. quellen lassen.', 'Mit einer Gabel auflockern.', 'Gemüse und Minze untermischen.', 'Mit Olivenöl und Zitronensaft anmachen.'] },
}

export function getRecipeDetail(id: string): RecipeDetail {
  return recipeDetails[id] ?? { servings: '2 Portionen', ingredients: ['Zutaten werden noch ergänzt'], steps: ['Zubereitung wird noch ergänzt'] }
}
